version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: my-mysql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: admin123!
      MYSQL_DATABASE: order
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  redis_data:
  mysql_data:

networks:
  app-network:
